<?php

namespace Tests\Unit\Models;

use App\Comment;
use App\Like;
use App\Traits\HasLikes;
use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class CommentTest extends TestCase
{
    use RefreshDatabase;
    public $comment;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->comment = factory(Comment::class)->create();
    }

    public function test_a_comment_belongs_to_a_user()
    {
        $comment = factory(Comment::class)->create();
        $this->assertInstanceOf(User::class, $comment->user);
    }

    public function test_a_comment_model_must_use_the_trait_has_likes()
    {
        $uses = class_uses(Comment::class);

        $this->assertArrayHasKey(HasLikes::class, $uses, 'Comment class must use HasLikes trait');
    }
}