<?php

namespace Tests\Unit\Models;

use App\Comment;
use App\Like;
use App\Status;
use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class StatusTest extends TestCase
{
    use RefreshDatabase;
    public $status;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->status = factory(Status::class)->create();
    }

    function test_a_status_belongs_to_a_user()
    {
        $status = factory(Status::class)->create();
        $this->assertInstanceOf(User::class, $status->user);
    }

    function test_a_status_has_many_comments()
    {
        $status = factory(Status::class)->create();
        factory(Comment::class)->create(['status_id' => $status->id]);
        $this->assertInstanceOf(Comment::class, $status->comments->first());
    }

}
