<?php

namespace Tests\Feature;

use App\Comment;
use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class CanLikeCommentsTest extends TestCase
{
    use RefreshDatabase;
    public $comment;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->comment = factory(Comment::class)->create();
    }


    public function test_guest_users_cannot_like_comments()
    {
        //$this->withoutExceptionHandling();

        $response = $this->postJson(route('comments.likes.store', $this->comment));
        $response->assertStatus(401);
    }

    public function test_an_authenticated_user_can_like_and_unlike_comments()
    {
        //$this->markTestIncomplete();

        $this->withoutExceptionHandling();

        $user = factory(User::class)->create();

        $this->assertCount(0, $this->comment->likes);

        $this->actingAs($user)->postJson(route('comments.likes.store', $this->comment));

        $this->assertCount(1, $this->comment->fresh()->likes);

        $this->assertDatabaseHas('likes', ['user_id' => $user->id,]);

        $this->actingAs($user)->deleteJson(route('comments.likes.destroy', $this->comment));

        $this->assertCount(0, $this->comment->fresh()->likes);

        $this->assertDatabaseMissing('likes', ['user_id' => $user->id,]);
    }
}
